dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.3
